### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by NoMrBond**
Fix NRM orientation and DXT5nm format

### CODE REVIEW

**Comment by PhineasFreak** [comment]
Is this the same fix as the one from PR https://github.com/KSP-RO/ProceduralFairings-ForEverything/pull/5?

**Comment by NoMrBond** [comment]
I can't download the two .DDS files submitted with PR#5 to check, but it addresses the same two normal map files.  I confirmed the -x/DXT5nm formatting fix on those files addressed the lighting issues locally before submitting them, I forgot to check if there was a PR waiting which already addressed it though, sorry about that.

**Comment by PhineasFreak** [comment]
No, it's OK, i just confirming this since @KortexM has not been online for the last 9 months or so.

Thank you for the fix! I will ping @NathanKell in order to merge this PR and close the other one.

**Comment by NathanKell** [comment]
Ping? PONG!

**Comment by PhineasFreak** [comment]
Damn, that was fast! :smile:

**Comment by NathanKell** [comment]
^_^

Was AFK for a weekish but I'm back(ish) now. Feel free to poke anywhere else needed. :)

And thanks for the fix @NoMrBond !

**Pull request merged**
